spring.application.name=ibank_project

# ===== DataSource =====
spring.datasource.url=jdbc:postgresql://localhost:5432/ibank_db
spring.datasource.username=ibank_user
spring.datasource.password=ibank_pass
spring.datasource.driver-class-name=org.postgresql.Driver

# ===== JPA =====
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# 연결 풀 기본 isolation: READ_COMMITTED (PostgreSQL 기본값)
spring.jpa.properties.hibernate.connection.isolation=2

# ===== Actuator =====
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=when_authorized
